name: Publish Package to npmjs
on:
  release:
    types: [published]
permissions:
  id-token: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Checkout code
      
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v4
        name: Setup node
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'

      - uses: pnpm/action-setup@v3
        name: Install pnpm
        with:
          version: 8
          run_install: true

      - run: pnpm run build
        name: Build

      - run: npm publish --provenance
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}